### ISSUE TITLE
Ctenophores have anal pores, are they homologous?

### ISSUE THREAD

**Issue by cmungall** [BgeeDB/anatomical-similarity-annotations#15]
anal pore in cteno: http://purl.obolibrary.org/obo/CTENO_0000033 

New evidence that this is functionally an anus:
http://www.sciencemag.org/news/2016/03/why-watching-comb-jellies-poop-has-stunned-evolutionary-biologists

No publication yet, this is a report of a meeting [Ctenopolooza](http://ctenopalooza.whitney.ufl.edu/) (which is an awesome name, and looks like it was a fascinating meeting too, cc @beroe).

Of course, even with evidence that this is functionally an anus, it doesn't follow it's homologous to the bilaterian anus (if the bilaterian anus is homologous..), but it seems a possible hypothesis that should be recorded in bgee)

**Comment by ANiknejad** [comment]
Thank you, Chris, now this amazing stuff is recorded.
Cheers,
Anne
