### ISSUE TITLE
middle ear NOT homologous in Mammals

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/anatomical-similarity-annotations#19]
(copy/paste from my mail 5 sept. 2016 à 18:17)
Recent articles

http://www.ncbi.nlm.nih.gov/pubmed/27563341

'Resolving the evolution of the mammalian middle ear using Bayesian inference.'

"Our results support a simple, biologically plausible scenario without reversals. The middle ear bones detach from the postdentary trough only twice among mammals, once each in the ancestors of therians and monotremes. Disappearance of Meckel's cartilage occurred independently in numerous lineages from the Late Jurassic to the Late Cretaceous. This final separation is recapitulated during early development of extant mammals, while the earlier-occurring disappearance of a postdentary trough is not."

http://www.ncbi.nlm.nih.gov/pubmed/27228358

'Ear ossicle morphology of the Jurassic euharamiyidan Arboroharamiya and evolution of mammalian middle ear'

"Given this phylogeny, development of the DMME [definitive mammalian middle ear] took place once in the allotherian clade containing euharamiyidans and multituberculates, probably independent to those of monotremes and therians. Thus, the DMME has evolved at least three times independently in mammals."

Does this scenario mean mammalian middle ear is in fact not homologous through all Mammals, like we claimed until now with 'high confidence' ? (and NOT in Amniota)

**Comment by ANiknejad** [comment]
Answer from Marc RR:
Interesting, thanks. At the least it means that there is conflicting evidence.

**Comment by ANiknejad** [comment]
@fbastian 

does it mean to lower the current single annotation level from High confidence to Medium, or will your algo do that for the global scoring when considering the new conflict? I am not comfortable to still have High confidence in my file even for single evidence, after reading these papers.

**Comment by ANiknejad** [comment]
@fbastian 
also do we have to use another ECO than 'non-traceable author statement' to report 'Resolving the evolution of the mammalian middle ear using Bayesian inference' ? maybe 

ECO:0000245
Preferred Name  computational combinatorial evidence used in manual assertion
Synonyms    inferred from reviewed computational analysis   RCA

Currently (for this 'middle ear' example reported by Bayesian inference) I annotated with 'non-traceable author statement'

@fbastian 
see here the HELO ontology (HypothEsis and Law Ontology) 
(HypothEsis and Law Ontology)

**Comment by ANiknejad** [comment]
> does it mean to lower the current single annotation level from High confidence to Medium, or will your algo do that for the global scoring when considering the new conflict? I am not comfortable to still have High confidence in my file even for single evidence, after reading these papers.

Fred's answer: no, we conserve the high level associated to this evidence at time of the annotation, and we annotate the conflict

**Comment by fbastian** [comment]
I realize that we could also retire the old annotation, if the evidence is proven to be wrong. This is what they do in GO annotations. But I don't think the old evidence is proven wrong, right?

**Comment by ANiknejad** [comment]
there is just new hypothesis based on recent evidences, but...
