### ISSUE TITLE
Newline needs to be escaped ln362-363

### ISSUE THREAD

**Issue by cmungall** [BgeeDB/anatomical-similarity-annotations#2]
The phrase

"Evolutionary events that may have led to the development of the Malpighian corpuscle of the vertebrate nephron: (…)C: The coelomic chamber becomes the capsule of Bowman, which surrounds the glomerulus, and a Malpighian
corpuscle is formed. The renal tubule connects to the coelom via ciliated peritoneal funnels. This is the situation in the mesonephros of adult salamanders and caecilians."

is split over two lines

**Comment by fbastian** [comment]
Reopen until @ANiknejad corrects our edit version.

**Comment by ANiknejad** [comment]
correction done
