### ISSUE TITLE
how to annotate a structure appearing in one taxon?

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/anatomical-similarity-annotations#26]
(related to issues #4 and #5 )

Using our current pipeline, I am not sure to understand how to annotate a structure reported as taxon-specific, let see example here:

'**Epibranchial placode homologues have also not been identified outside the vertebrates**. Indeed, taste buds, one of the structures innervated by epibranchial neurones, are believed to be vertebrate-specific. It should be noted, however, that the epibranchial placodes develop adjacent to the branchial slits, structures which in ascidians form after metamorphosis and are relatively poorly studied.'

UBERON:0003078 epibranchial placode

I would do a positive annotation on Vertebrate ...but also a negative annotation on Chordata (to limit appearance of the structure on sub-taxon Vertebrata) but regarding issues #4 and #5  it seems not correct to put NOT on parent Chordata, isn't it? specially because the 'epibranchial placode' may have a taxon constraint on Vertebrata, and putting an annotation on Chordata will generate an error in our pipeline.

But in the same way, putting negative annotation on sister taxa Cephalochorda and Tunicata could also generate an error

**Comment by fbastian** [comment]
If this structure is vertebrate-specific, then there is no plausible homology hypothetis at the chordata level, so you don't need the NOT annotation.
